### ISSUE TITLE
Physics bodies do not always get cleaned up

### ISSUE THREAD

**Issue by dgfitch** [jpfed/Adrift#26]
You can see this easier if an enemy is near a floor and drops a powerup. Sometimes the old body is still there after it is done exploding. Not sure what causes this.

**Comment by jpfed** [comment]
This was actually part of my motivation for "corpses" that would get eaten by grasshoppers or spore-fungi: then you would be able to see the thing that's getting in your way as you attempt to pick up the powerup. :P 

If we're lucky, the GC issues will be automagically taken care of in 0.6.  If not, it's hard to see a way to fix this other than replacing LOVE with our own framework that embeds Lua in C.

Note that even if you aren't holding a reference to a physics object, it won't get GCed for a little bit, which is why when we did our first sidescroller tests it was so hard to see why the objects were getting GCed- they would stick around for a little bit before suddenly becoming "immaterial".
